// Generates ui/gen/brands.js - the OS/appliance glyphs for a jack's `os = "..."`.
// Brand marks come from simple-icons (CC0, fill paths); anything without one falls
// back to a Lucide shape. `npm run brands` after editing either list.
import { mkdirSync, writeFileSync } from "node:fs";
import * as si from "simple-icons";

// key in the config  ->  simple-icons slug
const BRANDS = {
  ubuntu: "Ubuntu",
  debian: "Debian",
  linux: "Linux",
  alpine: "Alpinelinux",
  arch: "Archlinux",
  fedora: "Fedora",
  redhat: "Redhat",
  centos: "Centos",
  freebsd: "Freebsd",
  macos: "Apple",
  raspberrypi: "Raspberrypi",
  synology: "Synology",
  qnap: "Qnap",
  unraid: "Unraid",
  truenas: "Truenas",
  proxmox: "Proxmox",
  docker: "Docker",
  kubernetes: "Kubernetes",
  openwrt: "Openwrt",
  pfsense: "Pfsense",
  opnsense: "Opnsense",
  mikrotik: "Mikrotik",
  ubiquiti: "Ubiquiti",
  netgear: "Netgear",
  homeassistant: "Homeassistant",
  nextcloud: "Nextcloud",
  postgres: "Postgresql",
  gitlab: "Gitlab",
};

// simple-icons dropped Microsoft's logos over trademark, so the Windows flag is drawn here.
const CUSTOM = {
  windows:
    "M0 3.449 9.75 2.1v9.451H0m10.949-9.602L24 0v11.4H10.949M0 12.6h9.75v9.451L0 20.699" +
    "M10.949 12.6H24V24l-12.9-1.801",
};

// No mark at all (not a brand) - use a Lucide name instead.
const FALLBACKS = {
  router: "router",
  switch: "network",
  nas: "hard-drive",
  vm: "box",
  container: "container",
  printer: "printer",
  camera: "cctv",
  server: "server",
};

// simple-icons carries each brand's official colour; [colors] can override it.
const CUSTOM_COLORS = { windows: "#0078D4" };
const CUSTOM_LABELS = { windows: "Windows", macos: "macOS" };
// Generic kinds aren't brands, so their casing is ours to pick.
const FALLBACK_LABELS = {
  router: "Router",
  switch: "Switch",
  nas: "NAS",
  vm: "VM",
  container: "Container",
  printer: "Printer",
  camera: "Camera",
  server: "Server",
};

const brands = { ...CUSTOM };
const colors = { ...CUSTOM_COLORS };
// simple-icons knows how each brand writes its own name, so the suggestions read properly.
const labels = { ...CUSTOM_LABELS };
for (const [key, slug] of Object.entries(BRANDS)) {
  const entry = si[`si${slug}`];
  if (!entry) throw new Error(`simple-icons has no si${slug} - fix scripts/brands.mjs`);
  brands[key] = entry.path;
  if (entry.hex) colors[key] = `#${entry.hex}`;
  if (entry.title && !labels[key]) labels[key] = entry.title;
}
for (const [k, v] of Object.entries(FALLBACK_LABELS)) labels[k] = v;

mkdirSync("ui/gen", { recursive: true });
writeFileSync(
  "ui/gen/brands.js",
  `// Generated by scripts/brands.mjs - do not edit. Marks from simple-icons (CC0).\n` +
    `// Regenerate with: npm run brands\n` +
    `const BRANDS = ${JSON.stringify(brands, null, 0)};\n` +
    `const BRAND_FALLBACKS = ${JSON.stringify(FALLBACKS, null, 0)};\n` +
    `const BRAND_COLORS = ${JSON.stringify(colors, null, 0)};\n` +
    `const OS_CHOICES = ${JSON.stringify(
      [...new Set([...Object.keys(brands), ...Object.keys(FALLBACKS)])]
        .map((k) => labels[k] ?? k)
        .sort((a, b) => a.localeCompare(b)),
    )};\n`,
);
console.log(
  `wrote ui/gen/brands.js (${Object.keys(brands).length} marks, ${Object.keys(FALLBACKS).length} fallbacks)`,
);
