// Generates ui/gen/brands.js — the OS/appliance glyphs for a jack's `os = "..."`.
// Brand marks come from simple-icons (CC0, fill paths); anything without one falls
// back to a Lucide shape. `npm run brands` after editing either list.
import { mkdirSync, writeFileSync } from "node:fs";
import * as si from "simple-icons";

// key in the config  ->  simple-icons slug
const BRANDS = {
  ubuntu: "Ubuntu", debian: "Debian", linux: "Linux", alpine: "Alpinelinux",
  arch: "Archlinux", fedora: "Fedora", redhat: "Redhat", centos: "Centos",
  freebsd: "Freebsd", macos: "Apple", raspberrypi: "Raspberrypi",
  synology: "Synology", qnap: "Qnap", unraid: "Unraid", truenas: "Truenas",
  proxmox: "Proxmox", docker: "Docker", kubernetes: "Kubernetes",
  openwrt: "Openwrt", pfsense: "Pfsense", opnsense: "Opnsense",
  mikrotik: "Mikrotik", ubiquiti: "Ubiquiti", netgear: "Netgear",
  homeassistant: "Homeassistant", nextcloud: "Nextcloud",
  postgres: "Postgresql", gitlab: "Gitlab",
};

// No simple-icons mark (trademark, or just not a brand) — use a Lucide name instead.
const FALLBACKS = {
  windows: "app-window",
  router: "router",
  switch: "network",
  nas: "hard-drive",
  vm: "box",
  container: "container",
  printer: "printer",
  camera: "cctv",
  server: "server",
};

const brands = {};
for (const [key, slug] of Object.entries(BRANDS)) {
  const entry = si[`si${slug}`];
  if (!entry) throw new Error(`simple-icons has no si${slug} — fix scripts/brands.mjs`);
  brands[key] = entry.path;
}

mkdirSync("ui/gen", { recursive: true });
writeFileSync(
  "ui/gen/brands.js",
  `// Generated by scripts/brands.mjs — do not edit. Marks from simple-icons (CC0).\n` +
    `// Regenerate with: npm run brands\n` +
    `const BRANDS = ${JSON.stringify(brands, null, 0)};\n` +
    `const BRAND_FALLBACKS = ${JSON.stringify(FALLBACKS, null, 0)};\n` +
    `const OS_CHOICES = ${JSON.stringify([...Object.keys(BRANDS), ...Object.keys(FALLBACKS)].sort())};\n`,
);
console.log(`wrote ui/gen/brands.js (${Object.keys(brands).length} marks, ${Object.keys(FALLBACKS).length} fallbacks)`);
