// Pulls the handful of Lucide icons the UI uses out of lucide-static and writes
// ui/gen/icons.js. Same artwork as lucide-react, without React or a bundler —
// `npm run icons` after editing USED, and commit the result.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const USED = [
  "layers",         // All jacks
  "folder",
  "folder-open",
  "chevron-right",  // tree disclosure
  "tag",
  "circle-off",     // Untagged
  "server",         // a jack
  "search",
  "waypoints",      // route
  "arrow-right-left", // port forwards
  "plug",           // reachable
  "square-terminal", // connect
  "copy",
  "check",
  "file-pen-line",  // edit config
  "download",       // import from an ssh config
  "plus",
  "pencil",
  "trash-2",
  "x",
  "folder-plus",
  "external-link",
  "globe",
  "monitor",
  "screen-share",  // vnc
  "unplug",
  "settings",
  "router",
  "network",
  "hard-drive",
  "box",
  "container",
  "printer",
  "cctv",
  "rotate-cw",     // try that again
  "arrow-up",      // up a folder
];

const inner = (name) =>
  readFileSync(`node_modules/lucide-static/icons/${name}.svg`, "utf8")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/\s+/g, " ")
    .trim();

const body = USED.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(inner(n))},`).join("\n");
mkdirSync("ui/gen", { recursive: true });
writeFileSync(
  "ui/gen/icons.js",
  `// Generated by scripts/icons.mjs — do not edit. Lucide (ISC), see node_modules/lucide-static.\n` +
    `// Regenerate with: npm run icons\n` +
    `const ICONS = {\n${body}\n};\n`,
);
console.log(`wrote ui/gen/icons.js (${USED.length} icons)`);
